---
# yamllint disable rule:truthy
version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: main
    labels:
      - "changes/patch"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: main
    labels:
      - "changes/patch"
    groups:
      all:
        patterns:
          - "*"
  
  # Updates for infrahub-sdk at 8 AM
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    target-branch: develop
    labels:
      - "changes/patch"
    groups:
      infrahub-sdk:
        patterns:
          - "infrahub-sdk"

  # Updates for infrahub-sdk at 12 PM
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
    target-branch: develop
    labels:
      - "changes/patch"
    groups:
      infrahub-sdk:
        patterns:
          - "infrahub-sdk"

  # Updates for infrahub-sdk at 4 PM
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:00"
    target-branch: develop
    labels:
      - "changes/patch"
    groups:
      infrahub-sdk:
        patterns:
          - "infrahub-sdk"
