# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install containerlab
    init: bash -c "$(curl -sL https://get.containerlab.dev)" # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds

  - name: Download cEOS
    init: curl https://www.arista.com/surl/Qyhs69V8R --output ceos.tar.xz

  - name: Import cEOS image
    init: docker import ceos.tar.xz ceosimage:4.29.M5

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
