# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full
# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install dependencies
    command: >
      pip install ansible &&
      ansible-galaxy collection install arista.avd &&
      bash -c "$(curl -sL https://get.containerlab.dev)" &&

      curl https://www.arista.com/surl/Qyhs69V8R --output ceos.tar.xz &&
      docker import ceos.tar.xz ceosimage:4.29.M5 &&

      git clone https://github.com/arista-netdevops-community/avd-cEOS-Lab &&

      cd avd-cEOS-Lab/alpine_host && chmod +x build.sh && ./build.sh &&

      gp sync-done ready

  - name: Deploy and configure lab
    command: >
      gp sync-await ready &&
      sudo containerlab deploy -t avd-cEOS-Lab/labs/evpn/avd_asym_irb/topology.yaml &&
      ansible-playbook avd-cEOS-Lab/labs/evpn/avd_asym_irb/playbooks/fabric-deploy-config.yaml --inventory avd-cEOS-Lab/labs/evpn/avd_asym_irb/inventory.yaml

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
