---
rfiles:
  - name: device_startup
    description: "Template to generate startup configuration for network devices"
    query: "device_startup_query"
    repository: "self"
    template_path: "templates/device_startup_config.j2"

  - name: clab_topology
    description: "Template to generate clab device topology"
    query: "topology_info_query"
    repository: "self"
    template_path: "topology/clab_topology.j2"
