[tool.poetry]
name = "naf-demo"
version = "0.1.0"
description = ""
authors = ["OpsMill <info@opsmill.com>"]

[tool.poetry.dependencies]
python = "^3.9, < 3.12"
infrahub = {path = "../infrahub", develop=true}
infrahub-sdk = {path = "python_sdk", develop=true}
invoke = "^2.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"