---
version: "3.4"

services:
  message-queue:
    image: rabbitmq:3.12-management
    environment:
      - "RABBITMQ_DEFAULT_USER=infrahub"
      - "RABBITMQ_DEFAULT_PASS=infrahub"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3

  cache:
    image: redis:7.2
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 3

  database:
    image: neo4j:5.13-community
    environment:
      - "NEO4J_AUTH=neo4j/admin"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      - "NEO4J_dbms_security_auth__minimum__password__length=4"
    volumes:
      - "./plugins:/plugins"
      - "database_data:/data"
      - "database_logs:/logs"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 2s
      timeout: 10s
      retries: 20
      start_period: 3s

  infrahub-server:
    image: 9r2s1098.c1.gra9.container-registry.ovh.net/opsmill/infrahub-py3.11:0.8.1-init
    command: gunicorn --config backend/infrahub/serve/gunicorn_config.py --logger-class infrahub.serve.log.GunicornLogger infrahub.server:app
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=INFO"
      - "INFRAHUB_SECURITY_INITIAL_ADMIN_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec"
      - "INFRAHUB_SECURITY_SECRET_KEY=327f747f-efac-42be-9e73-999f08f86b92"
      - "INFRAHUB_ALLOW_ANONYMOUS_ACCESS=true"
      - "PROMETHEUS_MULTIPROC_DIR=/prom_shared"
      - "INFRAHUB_FRONTEND_DIRECTORY=/opt/infrahub/frontend"
      - "INFRAHUB_DB_TYPE=neo4j"
    ports:
      - "8000:8000"
    volumes:
      - "storage_data:/opt/infrahub/storage"
    tty: true
    healthcheck:
      test: wget -O /dev/null http://localhost:8000/api/schema || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  infrahub-git:
    deploy:
      mode: replicated
      replicas: 2
    image: 9r2s1098.c1.gra9.container-registry.ovh.net/opsmill/infrahub-py3.11:0.8.1-init
    command: infrahub git-agent start --debug
    restart: unless-stopped
    depends_on:
      - infrahub-server
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_ADDRESS=http://infrahub-server:8000"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=DEBUG"
      - "INFRAHUB_SDK_API_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec"
      - "INFRAHUB_SDK_TIMEOUT=20"
      - "INFRAHUB_DB_TYPE=neo4j"
    volumes:
      - "git_data:/opt/infrahub/git"
      - "git_remote_data:/remote"
    tty: true

volumes:
  database_data:
  database_logs:
  git_data:
  git_remote_data:
  storage_data:
