---
plugin: opsmill.infrahub.inventory
api_endpoint: "http://localhost:8000"

strict: true

branch: "main"

nodes:
  InfraDevice:
    include:
      - id
      - name
      - primary_address
      - site
      - role

compose:
  hostname: name
  # platform_os: platform.ansible_network_os
  ansible_host: primary_address.address | ansible.utils.ipaddr('address')

keyed_groups:
  - prefix: site
    key: site.name
  - prefix: role
    key: role.name
  # - prefix: platform
  #   key: platform_os
