plugin: opsmill.infrahub.inventory
api_endpoint: "http://localhost:8000"
token: 06438eb2-8019-4776-878c-0941b1f1d1ec
validate_certs: True

strict: True

branch: "main"

nodes:
  InfraDevice:
    include:
      - name
      - platform
      - primary_address
      - interfaces
      - site

compose:
  hostname: name
  platform: platform.ansible_network_os
  ansible_host: primary_address
