---
# Inventory can be test with : ansible-inventory -i playbooks/inventory.yml  -y --list

plugin: opsmill.infrahub.inventory
api_endpoint: "http://localhost:8000"
timeout: 30

strict: false
# branch: "main"

nodes:
  InfraDevice:
    include:
      - id
      - name
      - site
      - role
      - platform
      - primary_address

compose:
  hostname: name
  ansible_host: primary_address.address | ansible.utils.ipaddr('address')

keyed_groups:
  - prefix: role
    key: role
  - prefix: site
    key: site.name
  - prefix: platform
    key: platform.ansible_network_os
