---
plugin: opsmill.infrahub.inventory
api_endpoint: "http://localhost:8000"
token: 06438eb2-8019-4776-878c-0941b1f1d1ec
validate_certs: False

# strict: True

branch: "main"

nodes:
  InfraDevice:
    include:
      - name
      - platform
      - primary_address

compose:
  hostname: name
  platform: platform.ansible_network_os
  ansible_host: primary_address.address | ansible.utils.ipaddr('address')
